name: yald
version: 0.0.2
description: Yet Another Logger for Dart
homepage: https://github.com/srikrishnacj/yald
repository: https://github.com/srikrishnacj/yald

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
